### ISSUE TITLE
Private marked properties missing

### ISSUE THREAD

**Issue by Timbuktu1982** [EnterTheNameHere/esdoc-monorepo#13]
Hi there,

when i mark a property as private, the doc generator ignores that property.

e.g. #nameOfProperty is missing in documentation.

Thx

**Comment by EnterTheNameHere** [comment]
Hi!

Do you mean the private fields, private methods and accessors in javascript (ES2022 I think):

`class Example {
    #secret = '42';
    
    get #message() {
        return `The answer is ${this.#secret}!`;
    }

    #sayAnswer() {
        console.log(this.#message);
    }

    constructor() {
        this.#sayAnswer();
    }
}

let example = new Example(); // The answer is 42!`

I'm looking into this right now.

1. ESDoc uses Babel as parser internally, which I would like to move outside of Core module, to allow different parsers too, like Typescript.
2. Both the Core module and the ecmascript-proposal-plugin have config for the parser hardcoded
3. The ESDoc was written at the time Babel 6 was used; That's many ESxxxx ago, when many proposals were experimental

Right now I'm thinking of using following process:
- allow user to set version in ESDoc config; cons: this will override any configuration user in reality uses, or user might forget to update this; there is already many config files where we re-specify the same setting/field; I would like to get as many config from already existing config files as possible to ease setting ESDoc up, like providing wizard interface, so you can basically forget about ESDoc config and still get what you want;
- if not specified in ESDoc config, look for parser user might use (if user transcribes code); if possible, use this parser, if not use default parser (Babel)
- look for user's parser config; use this config
- or if not possible, look for engine specified in package.json (like node version 12);
- or if not possible, use hardcoded default settings (that's what ESDoc does now)

I'm now looking at what would be best interface for Parser and ESTree/ASTTree to allow use of multiple parsers, like for Typescript;
then I need to look at config files of various tools/frameworks; Babel is easy, that can be used right away to parse file, then eg. eslint etc.

I think this way would be optimal for parsing files with the features user use; it would solve issues coming from experimental features changing during staging process like decorators which right now can be parsed in 3 different ways.

I'll probably set default values to node 12 version, which also includes #private syntax, to get most features... Have to write tests for that too.
